"""Draws the BusNearby Home Screen icon and writes worker/app-icons.js (base64 PNGs).

Run from anywhere: python3 -I scripts/build-app-icons.py
iOS rounds the corners itself, so the icon is a full square.
"""
import base64
import io
import pathlib

from PIL import Image, ImageDraw

BLUE = (0, 113, 227)
WHITE = (255, 255, 255)
S = 1024  # drawn large, then scaled down for smooth edges


def draw():
    img = Image.new('RGB', (S, S), BLUE)
    d = ImageDraw.Draw(img)
    # Bus front: body, windscreen, headlights, wheels, mirrors
    d.rounded_rectangle((262, 190, 762, 780), radius=90, fill=WHITE)
    d.rounded_rectangle((322, 290, 702, 540), radius=36, fill=BLUE)
    d.rounded_rectangle((372, 222, 652, 256), radius=17, fill=BLUE)
    d.ellipse((330, 610, 410, 690), fill=BLUE)
    d.ellipse((614, 610, 694, 690), fill=BLUE)
    d.rounded_rectangle((302, 740, 412, 850), radius=30, fill=WHITE)
    d.rounded_rectangle((612, 740, 722, 850), radius=30, fill=WHITE)
    d.rounded_rectangle((212, 300, 246, 420), radius=17, fill=WHITE)
    d.rounded_rectangle((778, 300, 812, 420), radius=17, fill=WHITE)
    return img


def png(img, size):
    buf = io.BytesIO()
    img.resize((size, size), Image.LANCZOS).save(buf, 'PNG', optimize=True)
    return base64.b64encode(buf.getvalue()).decode()


icon = draw()
out = pathlib.Path(__file__).resolve().parent.parent / 'worker' / 'app-icons.js'
out.write_text(
    '// Generated by scripts/build-app-icons.py — Home Screen icons for the web app.\n'
    f"export const APP_ICON_180 = '{png(icon, 180)}';\n"
    f"export const APP_ICON_512 = '{png(icon, 512)}';\n"
)
print(out, out.stat().st_size, 'bytes')
