#!/usr/bin/env python3
"""Builds worker/mrt-stations.js from the @olano/mcp-rail-sg npm package's data.js
(LTA station codes + data.gov.sg MRT/LRT station exits, Singapore Open Data Licence).

Usage: python3 -I scripts/build-mrt-stations.py path/to/package/dist/data.js
"""
import json, re, sys

src = open(sys.argv[1], encoding='utf8').read()
code_rows = re.findall(r"\['([A-Z]{2}\d+)', '([^']+)'", src[: src.index('EXIT_ROWS')])
exit_rows = re.findall(r"\['([^']+)', '[^']*', ([\d.]+), ([\d.]+)\]", src[src.index('EXIT_ROWS') : src.index('LTA_LINE_ROWS')])

def key(name):
    return re.sub(r'\s+(MRT|LRT)\s+STATION$', '', name.upper()).replace('-', ' ').strip()

stations = {}
for code, name in code_rows:
    st = stations.setdefault(key(name), {'name': name, 'codes': [], 'exits': []})
    if code not in st['codes']:
        st['codes'].append(code)
for name, lat, lon in exit_rows:
    if key(name) in stations:
        stations[key(name)]['exits'].append([round(float(lat), 5), round(float(lon), 5)])

missing = sorted(k for k, s in stations.items() if not s['exits'])
rows = [[s['name'], s['codes'], s['exits']] for s in stations.values() if s['exits']]
sys.stderr.write(f"{len(rows)} stations with exits; no exit data (left out): {missing}\n")

out = open('worker/mrt-stations.js', 'w', encoding='utf8')
out.write('// Generated by scripts/build-mrt-stations.py — do not edit by hand.\n')
out.write('// Source: LTA train station codes and data.gov.sg MRT/LRT station exits\n')
out.write('// (via the @olano/mcp-rail-sg package), Singapore Open Data Licence v1.0.\n')
out.write('// Rows: [station name, station codes, exit coordinates [lat, lon]].\n')
out.write('export const MRT_STATIONS = [\n')
for r in rows:
    out.write('  ' + json.dumps(r, ensure_ascii=False, separators=(',', ':')) + ',\n')
out.write('];\n')
